public class Calculator {
    /* Sums 2 numbers */
    public static integer sum(integer left, integer right) {
        return left + right;
    }
    
    public static integer multiply(integer left, integer right) {
        return left * right;
    }
    
    public static integer subtract(integer left, integer right) {
        return left - right;
    }
    
    public static integer divisionRenamed2(integer left, integer right) {
        return left / right;
    }
    
    public static integer power(integer n, integer power) {
        return n;
    }
}